language: python
python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq rubygems

install:
  - sudo gem install compass
  - pip install -r dev-requirements.txt --use-mirrors

script: python setup.py --auto --skipdeps
